# Generated by Django 2.1.7 on 2024-03-20 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20240313_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twilio_auth_token', models.CharField(max_length=34)),
                ('twilio_account_sid', models.CharField(max_length=34)),
                ('name', models.CharField(max_length=75)),
                ('call_back_url', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'message_type',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=200, null=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
                ('send_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Phone')),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'phone_type',
            },
        ),
        migrations.CreateModel(
            name='SentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sent_status',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_number', models.CharField(max_length=15)),
                ('from_number', models.CharField(max_length=15)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
                ('message_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MessageType')),
            ],
            options={
                'db_table': 'sms',
            },
        ),
        migrations.CreateModel(
            name='SMSFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sms_file',
            },
        ),
        migrations.CreateModel(
            name='SMSOptIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
            ],
            options={
                'db_table': 'sms_opt_in',
            },
        ),
        migrations.CreateModel(
            name='SMSOptOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Account')),
            ],
            options={
                'db_table': 'sms_opt_out',
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processing', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('opt_in_pending', models.BooleanField(default=False)),
                ('send_date_time', models.DateTimeField()),
                ('force_send', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=4000, null=True)),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_queues', to='polls.SMS')),
            ],
            options={
                'db_table': 'sms_queue',
            },
        ),
        migrations.CreateModel(
            name='SMSReceived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_received', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.SMS')),
            ],
            options={
                'db_table': 'sms_received',
            },
        ),
        migrations.CreateModel(
            name='SMSSent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_sent', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sent_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.SentStatus')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_sent', to='polls.SMS')),
            ],
            options={
                'db_table': 'sms_sent',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PhoneType'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='polls.MessageType'),
        ),
        migrations.AddField(
            model_name='account',
            name='opt_in_confirmation_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_using_opt_in_confirmation', to='polls.Message'),
        ),
        migrations.AddField(
            model_name='account',
            name='opt_out_confirmation_message',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_using_opt_out_confirmation', to='polls.Message'),
        ),
        migrations.AddField(
            model_name='account',
            name='request_for_consent_message',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_using_request_for_consent', to='polls.Message'),
        ),
    ]
