# Generated by Django 2.1.7 on 2024-04-07 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20240407_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsConversation',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_column='PhoneNumber', max_length=15)),
                ('unread', models.BooleanField(default=True)),
                ('opted_out', models.BooleanField(default=False)),
                ('opted_in', models.BooleanField(default=False)),
                ('last_sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_conversations', to='polls.SMS')),
            ],
            options={
                'db_table': 'sms_conversation',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.AddField(
            model_name='smsconversation',
            name='survery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_conversations', to='polls.Survey'),
        ),
    ]
