# Generated by Django 2.1.7 on 2024-04-07 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20240407_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='polls.Phone'),
        ),
    ]
