# Generated by Django 2.1.7 on 2024-04-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_survey_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='account',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='send_from',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='type',
        ),
        migrations.DeleteModel(
            name='PhoneType',
        ),
    ]
