# Generated by Django 2.1.7 on 2024-04-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20240407_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.DeleteModel(
            name='SMSFile',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opt_in_confirmation_message',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opt_out_confirmation_message',
        ),
        migrations.RemoveField(
            model_name='account',
            name='request_for_consent_message',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='message_type',
        ),
        migrations.AddField(
            model_name='phone',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='polls.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='call_back_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageType',
        ),
    ]
