# Generated by Django 2.1.7 on 2024-04-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20240407_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsconversation',
            name='opted_in',
        ),
        migrations.RemoveField(
            model_name='smsconversation',
            name='opted_out',
        ),
    ]
