# Generated by Django 2.1.7 on 2024-04-07 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20240407_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.CharField(blank=True, max_length=160, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'survey_question',
            },
        ),
        migrations.AlterField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='polls.Survey'),
        ),
    ]
