# Generated by Django 2.1.7 on 2024-04-07 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20240407_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconversation',
            name='last_survey_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_conversations', to='polls.SurveyQuestion'),
        ),
    ]
