# Generated by Django 2.1.7 on 2024-04-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_smsconversation_last_survey_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsoptin',
            name='account',
        ),
        migrations.RemoveField(
            model_name='smsoptout',
            name='account',
        ),
        migrations.DeleteModel(
            name='SMSOptIn',
        ),
        migrations.DeleteModel(
            name='SMSOptOut',
        ),
    ]
