# Generated by Django 2.1.7 on 2024-04-20 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dark_mode', models.BooleanField(blank=True, default=True, null=True)),
                ('profile_photo_url', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_code',
            field=models.CharField(default=polls.models.generate_partial_uuid, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('start_code', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
