# Generated by Django 2.1.7 on 2024-04-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_surveyresponse_aspects'),
        ('polls', '0019_auto_20240420_0351'),
    ]

    operations = [
    ]
