# Generated by Django 2.1.7 on 2024-04-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_merge_20240420_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='polls.Survey'),
        ),
    ]
