# Generated by Django 2.1.7 on 2024-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_survey_qr_code_url'),
        ('polls', '0023_auto_20240420_0531'),
    ]

    operations = [
    ]
