# Generated by Django 2.1.7 on 2024-04-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_merge_20240420_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssent',
            name='sent_status',
        ),
        migrations.DeleteModel(
            name='SentStatus',
        ),
    ]
