# Generated by Django 2.1.7 on 2024-04-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20240421_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconversation',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
