# Generated by Django 2.1.7 on 2024-04-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_smsconversation_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_column='PhoneNumber', max_length=15)),
                ('unread', models.BooleanField(default=True)),
                ('closed', models.BooleanField(default=False)),
                ('last_sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='polls.SMS')),
                ('last_survey_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='polls.SurveyQuestion')),
                ('survery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='polls.Survey')),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.RemoveField(
            model_name='smsconversation',
            name='last_sms',
        ),
        migrations.RemoveField(
            model_name='smsconversation',
            name='last_survey_question',
        ),
        migrations.RemoveField(
            model_name='smsconversation',
            name='survery',
        ),
        migrations.DeleteModel(
            name='SmsConversation',
        ),
    ]
