# Generated by Django 2.1.7 on 2024-04-21 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20240421_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achieved_on',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='percent_complete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
