# Generated by Django 2.1.7 on 2024-04-21 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20240421_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsConversation',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sms_conversation',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='smsconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_conversations', to='polls.Conversation'),
        ),
        migrations.AddField(
            model_name='smsconversation',
            name='sms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_conversations', to='polls.SMS'),
        ),
        migrations.AlterUniqueTogether(
            name='smsconversation',
            unique_together={('sms', 'conversation')},
        ),
    ]
