# Generated by Django 2.1.7 on 2024-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20240421_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconversation',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
