# Generated by Django 2.1.7 on 2024-04-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20240422_0108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
