# Generated by Django 2.1.7 on 2024-04-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20240422_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='sms_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='polls.SmsConversation'),
        ),
    ]
