# Generated by Django 2.1.7 on 2024-04-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_surveyresponse_sms_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='sms_conversation',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='polls.Conversation'),
        ),
    ]
